// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/canonical.proto

package canonical

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPayload) Reset() {
	*x = TelemetryPayload{}
	mi := &file_proto_canonical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPayload) ProtoMessage() {}

func (x *TelemetryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_canonical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPayload.ProtoReflect.Descriptor instead.
func (*TelemetryPayload) Descriptor() ([]byte, []int) {
	return file_proto_canonical_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryPayload) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *TelemetryPayload) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TelemetryPayload) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type CommandPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Params        []byte                 `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandPayload) Reset() {
	*x = CommandPayload{}
	mi := &file_proto_canonical_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandPayload) ProtoMessage() {}

func (x *CommandPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_canonical_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandPayload.ProtoReflect.Descriptor instead.
func (*CommandPayload) Descriptor() ([]byte, []int) {
	return file_proto_canonical_proto_rawDescGZIP(), []int{1}
}

func (x *CommandPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CommandPayload) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type EventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPayload) Reset() {
	*x = EventPayload{}
	mi := &file_proto_canonical_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPayload) ProtoMessage() {}

func (x *EventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_canonical_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPayload.ProtoReflect.Descriptor instead.
func (*EventPayload) Descriptor() ([]byte, []int) {
	return file_proto_canonical_proto_rawDescGZIP(), []int{2}
}

func (x *EventPayload) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventPayload) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *EventPayload) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Message struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MessageId   string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	DeviceId    string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TimestampMs int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	SourceProto string                 `protobuf:"bytes,4,opt,name=source_proto,json=sourceProto,proto3" json:"source_proto,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_Telemetry
	//	*Message_Command
	//	*Message_Event
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	Metadata      map[string]string `protobuf:"bytes,20,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_canonical_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_canonical_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_canonical_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Message) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Message) GetSourceProto() string {
	if x != nil {
		return x.SourceProto
	}
	return ""
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetTelemetry() *TelemetryPayload {
	if x != nil {
		if x, ok := x.Payload.(*Message_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

func (x *Message) GetCommand() *CommandPayload {
	if x != nil {
		if x, ok := x.Payload.(*Message_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Message) GetEvent() *EventPayload {
	if x != nil {
		if x, ok := x.Payload.(*Message_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Telemetry struct {
	Telemetry *TelemetryPayload `protobuf:"bytes,10,opt,name=telemetry,proto3,oneof"`
}

type Message_Command struct {
	Command *CommandPayload `protobuf:"bytes,11,opt,name=command,proto3,oneof"`
}

type Message_Event struct {
	Event *EventPayload `protobuf:"bytes,12,opt,name=event,proto3,oneof"`
}

func (*Message_Telemetry) isMessage_Payload() {}

func (*Message_Command) isMessage_Payload() {}

func (*Message_Event) isMessage_Payload() {}

var File_proto_canonical_proto protoreflect.FileDescriptor

const file_proto_canonical_proto_rawDesc = "" +
	"\n" +
	"\x15proto/canonical.proto\x12\binterlink\"T\n" +
	"\x10TelemetryPayload\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"@\n" +
	"\x0eCommandPayload\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06params\x18\x02 \x01(\fR\x06params\"a\n" +
	"\fEventPayload\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xb2\x03\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12!\n" +
	"\fsource_proto\x18\x04 \x01(\tR\vsourceProto\x12:\n" +
	"\ttelemetry\x18\n" +
	" \x01(\v2\x1a.interlink.TelemetryPayloadH\x00R\ttelemetry\x124\n" +
	"\acommand\x18\v \x01(\v2\x18.interlink.CommandPayloadH\x00R\acommand\x12.\n" +
	"\x05event\x18\f \x01(\v2\x16.interlink.EventPayloadH\x00R\x05event\x12;\n" +
	"\bmetadata\x18\x14 \x03(\v2\x1f.interlink.Message.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayloadB\x1dZ\x1binterlink/internal/canonicalb\x06proto3"

var (
	file_proto_canonical_proto_rawDescOnce sync.Once
	file_proto_canonical_proto_rawDescData []byte
)

func file_proto_canonical_proto_rawDescGZIP() []byte {
	file_proto_canonical_proto_rawDescOnce.Do(func() {
		file_proto_canonical_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_canonical_proto_rawDesc), len(file_proto_canonical_proto_rawDesc)))
	})
	return file_proto_canonical_proto_rawDescData
}

var file_proto_canonical_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_canonical_proto_goTypes = []any{
	(*TelemetryPayload)(nil), // 0: interlink.TelemetryPayload
	(*CommandPayload)(nil),   // 1: interlink.CommandPayload
	(*EventPayload)(nil),     // 2: interlink.EventPayload
	(*Message)(nil),          // 3: interlink.Message
	nil,                      // 4: interlink.Message.MetadataEntry
}
var file_proto_canonical_proto_depIdxs = []int32{
	0, // 0: interlink.Message.telemetry:type_name -> interlink.TelemetryPayload
	1, // 1: interlink.Message.command:type_name -> interlink.CommandPayload
	2, // 2: interlink.Message.event:type_name -> interlink.EventPayload
	4, // 3: interlink.Message.metadata:type_name -> interlink.Message.MetadataEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_canonical_proto_init() }
func file_proto_canonical_proto_init() {
	if File_proto_canonical_proto != nil {
		return
	}
	file_proto_canonical_proto_msgTypes[3].OneofWrappers = []any{
		(*Message_Telemetry)(nil),
		(*Message_Command)(nil),
		(*Message_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_canonical_proto_rawDesc), len(file_proto_canonical_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_canonical_proto_goTypes,
		DependencyIndexes: file_proto_canonical_proto_depIdxs,
		MessageInfos:      file_proto_canonical_proto_msgTypes,
	}.Build()
	File_proto_canonical_proto = out.File
	file_proto_canonical_proto_goTypes = nil
	file_proto_canonical_proto_depIdxs = nil
}
