// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/canonical.proto

package canonical

import (
	reflect "reflect"
	sync "sync"

	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPayload) Reset() {
	*x = TelemetryPayload{}
	mi := &file_proto_canonical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPayload) String() string { return protoimpl.X.MessageStringOf(x) }
func (*TelemetryPayload) ProtoMessage()    {}

func (x *TelemetryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_canonical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TelemetryPayload) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *TelemetryPayload) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TelemetryPayload) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type CommandPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Params        []byte                 `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandPayload) Reset() {
	*x = CommandPayload{}
	mi := &file_proto_canonical_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandPayload) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CommandPayload) ProtoMessage()    {}

func (x *CommandPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_canonical_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommandPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CommandPayload) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type EventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPayload) Reset() {
	*x = EventPayload{}
	mi := &file_proto_canonical_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPayload) String() string { return protoimpl.X.MessageStringOf(x) }
func (*EventPayload) ProtoMessage()    {}

func (x *EventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_canonical_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventPayload) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventPayload) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *EventPayload) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	SourceProto   string                 `protobuf:"bytes,4,opt,name=source_proto,json=sourceProto,proto3" json:"source_proto,omitempty"`
	Payload       isMessage_Payload      `protobuf_oneof:"payload"`
	Metadata      map[string]string      `protobuf:"bytes,20,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_canonical_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Message) ProtoMessage()    {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_canonical_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Message) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Message) GetSourceProto() string {
	if x != nil {
		return x.SourceProto
	}
	return ""
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetTelemetry() *TelemetryPayload {
	if x != nil {
		if v, ok := x.Payload.(*Message_Telemetry); ok {
			return v.Telemetry
		}
	}
	return nil
}

func (x *Message) GetCommand() *CommandPayload {
	if x != nil {
		if v, ok := x.Payload.(*Message_Command); ok {
			return v.Command
		}
	}
	return nil
}

func (x *Message) GetEvent() *EventPayload {
	if x != nil {
		if v, ok := x.Payload.(*Message_Event); ok {
			return v.Event
		}
	}
	return nil
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isMessage_Payload interface{ isMessage_Payload() }

type Message_Telemetry struct {
	Telemetry *TelemetryPayload `protobuf:"bytes,10,opt,name=telemetry,proto3,oneof"`
}

type Message_Command struct {
	Command *CommandPayload `protobuf:"bytes,11,opt,name=command,proto3,oneof"`
}

type Message_Event struct {
	Event *EventPayload `protobuf:"bytes,12,opt,name=event,proto3,oneof"`
}

func (*Message_Telemetry) isMessage_Payload() {}
func (*Message_Command) isMessage_Payload()   {}
func (*Message_Event) isMessage_Payload()     {}

var File_proto_canonical_proto protoreflect.FileDescriptor

var (
	file_proto_canonical_proto_rawDescBytesOnce sync.Once
	file_proto_canonical_proto_rawDescData      []byte
	file_proto_canonical_proto_rawDescGZIPOnce  sync.Once
	file_proto_canonical_proto_rawDescGZIPData  []byte
)

func file_proto_canonical_proto_rawDescBytes() []byte {
	file_proto_canonical_proto_rawDescBytesOnce.Do(func() {
		fd := &descriptorpb.FileDescriptorProto{
			Name:    proto.String("proto/canonical.proto"),
			Package: proto.String("interlink"),
			Syntax:  proto.String("proto3"),
			Options: &descriptorpb.FileOptions{GoPackage: proto.String("interlink/internal/canonical")},
			MessageType: []*descriptorpb.DescriptorProto{
				{
					Name: proto.String("TelemetryPayload"),
					Field: []*descriptorpb.FieldDescriptorProto{
						{Name: proto.String("metric"), Number: proto.Int32(1), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), JsonName: proto.String("metric")},
						{Name: proto.String("value"), Number: proto.Int32(2), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_DOUBLE.Enum(), JsonName: proto.String("value")},
						{Name: proto.String("unit"), Number: proto.Int32(3), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), JsonName: proto.String("unit")},
					},
				},
				{
					Name: proto.String("CommandPayload"),
					Field: []*descriptorpb.FieldDescriptorProto{
						{Name: proto.String("action"), Number: proto.Int32(1), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), JsonName: proto.String("action")},
						{Name: proto.String("params"), Number: proto.Int32(2), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_BYTES.Enum(), JsonName: proto.String("params")},
					},
				},
				{
					Name: proto.String("EventPayload"),
					Field: []*descriptorpb.FieldDescriptorProto{
						{Name: proto.String("event_type"), Number: proto.Int32(1), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), JsonName: proto.String("eventType")},
						{Name: proto.String("severity"), Number: proto.Int32(2), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), JsonName: proto.String("severity")},
						{Name: proto.String("detail"), Number: proto.Int32(3), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), JsonName: proto.String("detail")},
					},
				},
				{
					Name: proto.String("Message"),
					Field: []*descriptorpb.FieldDescriptorProto{
						{Name: proto.String("message_id"), Number: proto.Int32(1), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), JsonName: proto.String("messageId")},
						{Name: proto.String("device_id"), Number: proto.Int32(2), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), JsonName: proto.String("deviceId")},
						{Name: proto.String("timestamp_ms"), Number: proto.Int32(3), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_INT64.Enum(), JsonName: proto.String("timestampMs")},
						{Name: proto.String("source_proto"), Number: proto.Int32(4), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), JsonName: proto.String("sourceProto")},
						{Name: proto.String("telemetry"), Number: proto.Int32(10), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_MESSAGE.Enum(), TypeName: proto.String(".interlink.TelemetryPayload"), OneofIndex: proto.Int32(0), JsonName: proto.String("telemetry")},
						{Name: proto.String("command"), Number: proto.Int32(11), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_MESSAGE.Enum(), TypeName: proto.String(".interlink.CommandPayload"), OneofIndex: proto.Int32(0), JsonName: proto.String("command")},
						{Name: proto.String("event"), Number: proto.Int32(12), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_MESSAGE.Enum(), TypeName: proto.String(".interlink.EventPayload"), OneofIndex: proto.Int32(0), JsonName: proto.String("event")},
						{Name: proto.String("metadata"), Number: proto.Int32(20), Label: descriptorpb.FieldDescriptorProto_LABEL_REPEATED.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_MESSAGE.Enum(), TypeName: proto.String(".interlink.Message.MetadataEntry"), JsonName: proto.String("metadata")},
					},
					OneofDecl: []*descriptorpb.OneofDescriptorProto{{Name: proto.String("payload")}},
					NestedType: []*descriptorpb.DescriptorProto{
						{
							Name: proto.String("MetadataEntry"),
							Field: []*descriptorpb.FieldDescriptorProto{
								{Name: proto.String("key"), Number: proto.Int32(1), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), JsonName: proto.String("key")},
								{Name: proto.String("value"), Number: proto.Int32(2), Label: descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(), Type: descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(), JsonName: proto.String("value")},
							},
							Options: &descriptorpb.MessageOptions{MapEntry: proto.Bool(true)},
						},
					},
				},
			},
		}
		data, err := proto.Marshal(fd)
		if err != nil {
			panic(err)
		}
		file_proto_canonical_proto_rawDescData = data
	})
	return file_proto_canonical_proto_rawDescData
}

func file_proto_canonical_proto_rawDescGZIP() []byte {
	file_proto_canonical_proto_rawDescGZIPOnce.Do(func() {
		file_proto_canonical_proto_rawDescGZIPData = protoimpl.X.CompressGZIP(file_proto_canonical_proto_rawDescBytes())
	})
	return file_proto_canonical_proto_rawDescGZIPData
}

var file_proto_canonical_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_canonical_proto_goTypes = []any{
	(*TelemetryPayload)(nil), // 0: interlink.TelemetryPayload
	(*CommandPayload)(nil),   // 1: interlink.CommandPayload
	(*EventPayload)(nil),     // 2: interlink.EventPayload
	(*Message)(nil),          // 3: interlink.Message
	nil,                      // 4: interlink.Message.MetadataEntry
}
var file_proto_canonical_proto_depIdxs = []int32{
	0, // 0: interlink.Message.telemetry:type_name -> interlink.TelemetryPayload
	1, // 1: interlink.Message.command:type_name -> interlink.CommandPayload
	2, // 2: interlink.Message.event:type_name -> interlink.EventPayload
	4, // 3: interlink.Message.metadata:type_name -> interlink.Message.MetadataEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_canonical_proto_init() }
func file_proto_canonical_proto_init() {
	if File_proto_canonical_proto != nil {
		return
	}
	file_proto_canonical_proto_msgTypes[3].OneofWrappers = []any{
		(*Message_Telemetry)(nil),
		(*Message_Command)(nil),
		(*Message_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_canonical_proto_rawDescBytes(),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_canonical_proto_goTypes,
		DependencyIndexes: file_proto_canonical_proto_depIdxs,
		MessageInfos:      file_proto_canonical_proto_msgTypes,
	}.Build()
	File_proto_canonical_proto = out.File
	file_proto_canonical_proto_goTypes = nil
	file_proto_canonical_proto_depIdxs = nil
}
